raster_data:
  dem_path: "/Users/dillonragar/data/cpra/AMP_NGOM2_DEM_60m_Bilinear_Resample.tif" # str
  wse_directory_path: "/Users/dillonragar/data/tmp/cpra/2ft-slr-sequence-dry"
  wse_domain_raster: "/Users/dillonragar/data/cpra/HECRAS_domain_60m.tif"
  veg_base_raster: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif" #str
  veg_keys: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif.vat.dbf"
  wpu_path: /Users/dillonragar/Library/CloudStorage/OneDrive-LynkerTechnologies/2024 CPRA Atchafalaya DSS/data/WPU_id_60m.tif # 60m domain with pixels labeled by WPU
  salinity_raster: #str (optional)
  veg_type_path: "/Users/dillonragar/data/cpra/AMP_VEG_S12_G510_AB_O_ANN_01_25_DATA/AMP_VEG_S12_G510_AB_O_ANN_01_25_DATA.nc" # VegTransition output folder
  flotant_marsh_raster: "/Users/dillonragar/data/cpra/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif"
  #flotant_marsh_keys: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif.vat.dbf"

simulation:
  water_year_start: 1951 # int
  water_year_end: 1975 # int
  wse_sequence_input: True # bool if WSE input is synthetic
  run_hsi: True
  hydro_domain_flag: True
  blue_crab_lookup_table: "/Users/dillonragar/data/cpra/seine_bluecrab_gamm_table_1dec.csv"
  
metadata:
  model: HSI
  scenario: "S12" # scenario info for plots and metadata
  group: G510
  wpu: ARS

output:
  output_base: "/Users/dillonragar/data/cpra/"



# Scenario codes (20250116)
# 01: Dry, base
# 02: Dry, +2' SLR
# 03: Moderate, base
# 04: Moderate, +2' SLR
# 05: Wet, base
# 06: Wet, +2' SLR