raster_data:
  dem_path: "/Users/dillonragar/data/cpra/AMP_NGOM2_DEM_60m_Bilinear_Resample.tif" # str
  #wse_directory_path: "/Users/dillonragar/data/tmp/cpra/base-sequence-dry"
  netcdf_hydro_path: "/Users/dillonragar/data/tmp/cpra/G999"
  wse_domain_raster: "/Users/dillonragar/data/cpra/HECRAS_domain_60m.tif"
  veg_base_raster: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif" #str
  veg_keys: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif.vat.dbf"
  #wpu_path: /Users/dillonragar/Library/CloudStorage/OneDrive-LynkerTechnologies/2024 CPRA Atchafalaya DSS/data/WPU_id_60m.tif # 60m domain with pixels labeled by WPU
  salinity_raster: #str (optional)
  veg_type_path: "/Users/dillonragar/data/cpra/AMP_VEGH_WY99_000_D_00_10_ANN_G900_AB_O_V12/AMP_VEGH_WY99_000_D_00_10_ANN_G900_AB_O_V12.nc" # VegTransition output folder
  flotant_marsh_raster: "/Users/dillonragar/data/cpra/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif"
  #flotant_marsh_keys: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif.vat.dbf"

simulation:
  water_year_start: 1963 # int
  water_year_end: 1972 # int
  wse_sequence_input: True # bool if WSE input is synthetic
  run_hsi: True
  # hydro_domain_flag: True
  blue_crab_lookup_table: "/Users/dillonragar/data/cpra/seine_bluecrab_gamm_table_1dec.csv"
  years_mapping:
    1: 2006
    3: 2022
    5: 2020
  

metadata:
  model: HSIH # H indicates HEC-RAS input
  sea_level_condition: "000" # 1.08ft or 0.328m SLR
  flow_scenario: "D" #"W"? # scenario info for plots and metadata
  group: G900
  wpu: ARS
  output_version: v13

output:
  output_base: "/Users/dillonragar/data/cpra/"
