# config.yaml

raster_data:
  dem_path: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/DEM/AMP_NGOM2_DEM_60m_Bilinear_Resample.tif" # str"
  wse_directory_path: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/data_out/2ft-slr-sequence-moderate"
  veg_base_raster: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/Vegetation/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif" #str
  veg_keys: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/Vegetation/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif.vat.dbf"
  wpu_path: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/WPU Boundary/WPU_id_60m.tif" # 60m domain with pixels labeled by WPU
  salinity_raster: #str (optional)
  veg_type_path: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/data_out/VegOut_20250115_132228" # VegTransition output folder
  #flotant_marsh_raster: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif"
  #flotant_marsh_keys: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/AMP_lndtyp_60m_Nearest_Resample/AMP_lndtyp_60m_Nearest_Resample.tif.vat.dbf"

simulation:
  water_year_start: 1981 # int
  water_year_end: 1982 # int
  wse_sequence_input: True # bool if WSE input is synthetic
  run_hsi: True

metadata:
  model: HSI
  scenario: "BaseWet" # scenario info for plots and metadata
  group: LNK
  wpu: ARS

output:
  output_base: "/Users/jessicagarrett/Documents/CPRA Royal 2024/GIS/data_out"