raster_data:
  dem_path: "/Users/dillonragar/data/cpra/AMP_NGOM2_DEM_60m_Bilinear_Resample.tif" # str
  #wse_directory_path: "/Users/dillonragar/data/tmp/cpra/2ft-slr-sequence-dry"
  wse_domain_raster: "/Users/dillonragar/data/cpra/HECRAS_domain_60m.tif"
  netcdf_hydro_path: "/Users/dillonragar/data/tmp/cpra/G999"
  veg_base_raster: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif" #str
  veg_keys: "/Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif.vat.dbf"
  wpu_grid: /Users/dillonragar/Library/CloudStorage/OneDrive-LynkerTechnologies/2024 CPRA Atchafalaya DSS/data/WPU_id_60m.tif # 60m domain with pixels labeled by WPU
  salinity_raster: #str (optional)
  veg_type_path: "/Users/dillonragar/data/cpra/AMP_VEG_S02_AB_O_ANN_01_25_DATA_20250321_141313/AMP_VEG_S02_AB_O_ANN_01_25_DATA.nc" # VegTransition output folder
  initial_maturity:  "/Users/dillonragar/data/tmp/cpra/AMP_Tree_Age/AMP_Tree_Age.tif"

polygon_data:
  wpu_polygons: /Users/dillonragar/data/tmp/cpra/Atchafalaya MP WPUs/Atchafalaya MP WPUs.shp

simulation:
  water_year_start: 1963 # int
  water_year_end: 1972 # int
  wse_sequence_input: True # bool if WSE input is synthetic
  years_mapping:
    1: 2006
    3: 2022
    5: 2020
  
metadata:
  model: VEGH
  sea_level_condition: "328" # 1.08ft or 0.328m SLR
  flow_scenario: "D" #"W"? # scenario info for plots and metadata
  group: G900
  wpu: ARS
  output_version: v12

output:
  output_base: "/Users/dillonragar/data/cpra/"