name: cpra_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - gdal
  - appdirs
  - boto3
  - dash
  - dash-bootstrap-components
  - nbformat
  - pip
  - python-dotenv
  - shapely
  - future
  - geojson
  - geopandas
  - ipykernel
  - isodate
  - matplotlib
  - numpy
  - pandas
  - plotly
  - requests
  - xarray
  - rioxarray
  - cartopy
  - pyyaml
  - mypy
  - geoviews
  - geocube